#!/usr/bin/env bash

if [ -d ~/bin ] ; then
   PATH=~/bin:"${PATH}"
fi

export EDITOR="vim"
export VISUAL="vim"

#PYTHONPATH="${PYTHONPATH}:$HOME/proyectos/github/utils27.py"

export PS1='\[\033[01;36m\]\u\[\033[01;37m\]@\h\[\033[01;35m\]\w\n\[\033[01;37m\]\$\[\033[01;00m\]'

set -o vi
